---
name: ldm
channels:
  - pytorch
  - defaults
dependencies:
  - pip:
      - absl-py==1.4.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - albumentations==0.4.3
      - altair==4.2.2
      - antlr4-python3-runtime==4.8
      - async-timeout==4.0.2
      - attrs==22.2.0
      - backports-zoneinfo==0.2.1
      - blinker==1.6
      - cachetools==5.3.0
      - charset-normalizer==3.1.0
      - click==8.1.3
      - cmake==3.26.1
      - decorator==5.1.1
      - einops==0.3.0
      - entrypoints==0.4
      - filelock==3.10.7
      - frozenlist==1.3.3
      - fsspec==2023.3.0
      - ftfy==6.1.1
      - future==0.18.3
      - gitdb==4.0.10
      - gitpython==3.1.31
      - google-auth==2.17.2
      - google-auth-oauthlib==1.0.0
      - grpcio==1.53.0
      - huggingface-hub==0.0.8
      - idna==3.4
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.2
      - imgaug==0.2.6
      - importlib-metadata==6.1.0
      - jinja2==3.1.2
      - joblib==1.2.0
      - jsonschema==4.17.3
      - kornia==0.5.0
      - lit==16.0.0
      - markdown==3.4.3
      - markdown-it-py==2.2.0
      - markupsafe==2.1.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.0.4
      - numpy==1.24.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - omegaconf==2.1.1
      - open-clip-torch==2.16.0
      - opencv-python==4.1.2.30
      - packaging==21.3
      - pandas==1.5.3
      - pkgutil-resolve-name==1.3.10
      - protobuf==3.20.3
      - pudb==2019.2
      - pyarrow==11.0.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pydeck==0.8.0
      - pydeprecate==0.3.1
      - pygments==2.14.0
      - pympler==1.0.1
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - pytorch-lightning==1.4.2
      - pytz==2023.3
      - pytz-deprecation-shim==0.1.0.post0
      - pyyaml==6.0
      - regex==2023.3.23
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - rich==13.3.3
      - rsa==4.9
      - sacremoses==0.0.53
      - scipy==1.9.1
      - semver==3.0.0
      - sentencepiece==0.1.97
      - smmap==5.0.0
      - streamlit==1.20.0
      - sympy==1.11.1
      - tensorboard==2.12.1
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6
      - test-tube==0.7.5
      - threadpoolctl==3.1.0
      - timm==0.6.11
      - tokenizers==0.10.3
      - toml==0.10.2
      - toolz==0.12.0
      - torch==2.0.0
      - torch-fidelity==0.3.0
      - torchmetrics==0.7.3
      - tornado==6.2
      - tqdm==4.65.0
      - transformers==4.6.0
      - triton==2.0.0
      - tzdata==2023.3
      - tzlocal==4.3
      - urllib3==1.26.15
      - urwid==2.1.2
      - validators==0.20.0
      - watchdog==3.0.0
      - wcwidth==0.2.6
      - werkzeug==2.2.3
      - yarl==1.8.2
