model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    embed_dim: 4
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5

    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0

    # first_stage_config:
    #   target: ldm.models.autoencoder.DualVQModelInterface
    #   params:
    #     embed_dim: 3
    #     n_embed: 8192
    #     # part_decoder: True
    #     ckpt_path: models/first_stage_models/vq-f4/model.ckpt
    #     ddconfig:
    #       double_z: false
    #       z_channels: 3
    #       resolution: 256
    #       in_channels: 3
    #       out_ch: 3
    #       ch: 128
    #       ch_mult:
    #       - 1
    #       - 2
    #       - 4
    #       num_res_blocks: 2
    #       attn_resolutions: []
    #       dropout: 0.0
    #     lossconfig:
    #       target: torch.nn.Identity

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    wrap: True
    train:
      target: ldm.data.base.ImagePaths
      params:
        size: 128
        # degradation: pil_nearest
        paths: "data/NYU/archive/nyu_data/data/NYU_train_text_depth.txt"
    validation:
      target: ldm.data.base.ImagePaths
      params:
        size: 128
        # degradation: pil_nearest
        paths: "data/NYU/archive/nyu_data/data/NYU_test_text_depth.txt"

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 50
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
