model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0205
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    image_size: 64
    channels: 3
    monitor: val/loss_simple_ema
    loss_type: l1

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 64
        attention_resolutions:
        # note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 64 for f4
        - 32
        - 16
        - 8
        num_res_blocks: 2
        channel_mult:
        - 1
        - 4
        - 8
        num_heads: 8
        linear_start: 0.0015
        linear_end: 0.0205
        timesteps: 1000
    first_stage_config:
      target: ldm.models.autoencoder.DualVQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        # part_decoder: True
        ckpt_path: models/first_stage_models/vq-f4/model.ckpt
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_unconditional__
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    wrap: True
    train:
      target: ldm.data.cityscapes.load_data
      params:
        dataset_mode: cityscapes
        data_dir: /root/data/cityscapes/
        image_size: 256
        random_crop: True
        random_flip: True
        is_train: True
    validation:
      target: ldm.data.cityscapes.load_data
      params:
        dataset_mode: cityscapes
        data_dir: /root/data/cityscapes/
        image_size: 256
        random_crop: False
        random_flip: False
        is_train: False


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True