model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0205
    log_every_t: 100
    timesteps: 1000
    loss_type: l1
    first_stage_key: image
    cond_stage_key: label
    image_size: 64
    channels: 3
    concat_mode: true
    cond_stage_trainable: true
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 6
        out_channels: 3
        model_channels: 64
        attention_resolutions:
        - 32
        - 16
        - 8
        num_res_blocks: 2
        channel_mult:
        - 1
        - 4
        - 8
        num_heads: 8
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        # part_decoder: True
        ckpt_path: models/first_stage_models/vq-f4/model.ckpt
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.dinov2Rescaler
      params:
        n_stages: 2
        in_channels: 3
        out_channels: 3
# data:
#   target: main.DataModuleFromConfig
#   params:
#     batch_size: 20
#     wrap: True
#     train:
#       target: ldm.data.semantic.load_data
#       params:
#         dataset_mode: celeba
#         data_dir: /data8/CelebAMask-HQ/
#         image_size: 256
#         random_crop: True
#         random_flip: True
#         is_train: True
#     validation:
#       target: ldm.data.semantic.load_data
#       params:
#         dataset_mode: celeba
#         data_dir: /data8/CelebAMask-HQ/
#         image_size: 256
#         random_crop: False
#         random_flip: False
#         is_train: False

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    wrap: True
    train:
      target: ldm.data.base.ImagePaths
      params:
        size: 256
        # degradation: pil_nearest
        paths: ["data/NYU/archive/nyu_data/data/NYU_train_text_rgb.txt", "data/NYU/archive/nyu_data/data/NYU_train_text_depth.txt"]
    validation:
      target: ldm.data.base.ImagePaths
      params:
        size: 256
        # degradation: pil_nearest
        paths: ["data/NYU/archive/nyu_data/data/NYU_test_text_rgb.txt", "data/NYU/archive/nyu_data/data/NYU_test_text_depth.txt"]


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 100
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True